### ISSUE TITLE
Homee integration does not work properly with new Homee version 2.40.2 (with 2.40.1 it was working)

### ISSUE THREAD

**Issue by Triplehxh** [Taraman17/hass-homee#105]
## Type of problem

- [x] I have a question.
- [x] A feature does not work as expected.
- [x] I found a bug (see error log below).

## Version

Homee 2.40.2
HomeAssistant 2024.9.3
homee Plugin in HA 2.7.0
## Detailed description
I was updating my Homee to the new version 2.40.2 Homee, HomeAssistant etc. was also restarted. I can see the devices but espacially the lights are all not working. Hopefully I sent you the correct part of the log. If anything else is needed please let me know

## Error log

```text

2024-09-27 07:15:11.379 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'homee' calls async_forward_entry_setup for integration, homee with title: 0005511505C2 (192.168.178.25) and entry_id: 6533fad6f5fb57dad2b3d597e0983c2d, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/homee/__init__.py, line 145: hass.async_create_task(, please create a bug report at https://github.com/Taraman17/hacs-homee/issues
2024-09-27 07:15:11.748 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from waterkotte_heatpump, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'waterkotte_heatpump' custom integration
2024-09-27 07:15:12.121 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.homee.light.HomeeLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 19> and color modes, please create a bug report at https://github.com/Taraman17/hacs-homee/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-09-27 07:15:12.121 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.homee.light.HomeeLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/Taraman17/hacs-homee/issues
2024-09-27 07:15:12.122 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.homee.light.HomeeLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 19> and color modes, please create a bug report at https://github.com/Taraman17/hacs-homee/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-09-27 07:15:12.122 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.homee.light.HomeeLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/Taraman17/hacs-homee/issues
2024-09-27 07:15:12.123 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration homee with title: 0005511505C2 (192.168.178.25) and entry_id: 6533fad6f5fb57dad2b3d597e0983c2d, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-09-27 07:15:12.128 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration homee with title: 0005511505C2 (192.168.178.25) and entry_id: 6533fad6f5fb57dad2b3d597e0983c2d, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2184, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)
2024-09-27 07:15:12.130 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entity binary_sensor.turkontakt_terasse_opening for domain binary_sensor with platform homee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1366, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homee/__init__.py", line 285, in state_attributes
    data = self._entity.__class__.__bases__[1].state_attributes.fget(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by Triplehxh** [comment]
![image](https://github.com/user-attachments/assets/be8a6671-73c2-46c1-92d7-4bec3f8bdd8e)
![image](https://github.com/user-attachments/assets/09a5f892-e05b-4ebd-b541-9cbf2d6287f1)

**Comment by Taraman17** [comment]
Hi,

you are using quite an old version of the homee integration there. Current one is 2.9.6.
At least the warnings logged there are fixed meanwhile.

Also the code referenced in the error message has changed till then.
So I assume, the error will be gone with the current version.

**Comment by Triplehxh** [comment]
> Hi,
> 
> you are using quite an old version of the homee integration there. Current one is 2.9.6. At least the warnings logged there are fixed meanwhile.
> 
> Also the code referenced in the error message has changed till then. So I assume, the error will be gone with the current version.

Thanks a lot. I dont know why (I was already on the "new" repo) but i never got an update shown up. I manually changed to the newest version in hacks and it worked!
