### ISSUE TITLE
Kann Master-homee nicht integrieren (Unknown Error)

### ISSUE THREAD

**Issue by JayJayXXX** [Taraman17/hass-homee#107]
Hi @Taraman17,

erstmal vielen Dank dafür, dass du diese Integration weiterführst. Ich war viele Jahre mit mehreren homee und insgesamt über 300 Aktoren und Sensoren unterwegs. Nun da mir ein Würfel kaputt gegangen ist und ich eh viele Geräte neu einlernen müsste habe ich mich zum teilweisen Umstieg auf HA entschieden.

Eigentlich wollte ich den Master-homee einbinden um gerade meine Enocengeräte weiter nutzen zu können, das klappt aber leider nicht, es wird nach langer Zeit nur ein "Unknown Error" ausgegeben. Meine Slave-homees konnte ich nach mehreren Anläufen aber problemlos integrieren. Gibt es eine Obergrenze für Geräte? (Beim Master sind es 354) Oder liegt es am Master selber?

**Comment by Taraman17** [comment]
Hi,

interessante Frage. Ich könnte mir vorstellen, dass der Master-Homee leicht andere Daten schickt als ein "normaler" oder Slave und die integration dann bei der Verarbeitung stolpert.

Um das untersuchen zu können, bräuchte ich möglichst umfangreiche Logfiles.

Könntest du bitte mal in der HA configuration.yaml folgendes einfügen:
logger:
  default: info
  logs:
    custom-components.homee: debug
    pymee: debug

Und mir nach einem Neustart von HA das entsprechende Log hier anhängen? Wenn dir das wegen eventuell enthaltener privater Daten zu heikel ist, auch gerne an Mozilla(at)Adrario.de schicken.

**Comment by JayJayXXX** [comment]
Mache ich sehr gern, wenn du mir sagst wo das Log gespeichert wird. Sorry, bin noch nicht so lange bei HA

**Comment by Taraman17** [comment]
Unter Einstellungen->System->Protokolle. 
Ganz unten "vollständige Protokolle herunterladen"

**Comment by Taraman17** [comment]
Kann ich dir noch Hilfestellung mit den Protokollen geben?

**Comment by neosantos84** [comment]
Hallo  @Taraman17 ,
ich hatte auch schon im homee-forum (jochen....) geschrieben, dass ich Probleme mit dem Master-homee habe. Alle anderen homees lassen sich einbinden. Ich würde dir gerne die Protokolle zukommen lassen. Bin aber schon allein zu blöd die yaml Datei zu editieren. Mein HomeAssistant läuft in der virtuellen Maschine auf ner Synology und ich verstehe nicht, wie ich auf die Daten der virtuellen Maschine zugreifen kann, um diese zu editieren.  Gibt es eine Möglichkeit aus HomeAssistant die yaml Datei zu editieren? Sorry, komme nur sporadisch dazu mich damit zu beschäftigen. Nutze aber schon die slave-homees und ich bin dir sehr dankbar, was du hinbekommen hast!

**Comment by Taraman17** [comment]
Hi,
Du kannst mittlerweile auch einfacher an die Logs kommen.
Wenn Du auf der "Geräte & Dienste" Seite auf den Homee Eintrag klickst, dann kannst Du auf der Homee Seite links unten "Debug protokoll aktivieren" klicken. Danach die Integration neu laden und das Log wieder deaktivieren.
Danach wird es Dir zum Download angeboten.

**Comment by neosantos84** [comment]
Hallo @Taraman17 ,

ich glaube das müsste das entsprechende Protokoll sein. Hoffe es hilft dir weiter:

Logger: homeassistant
Quelle: /usr/src/homeassistant/homeassistant/runner.py:112
Erstmals aufgetreten: 13:26:17 (3 Vorkommnisse)
Zuletzt protokolliert: 22:50:49

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pyHomee/__init__.py", line 167, in run
    await self.open_ws()
  File "/usr/local/lib/python3.13/site-packages/pyHomee/__init__.py", line 216, in open_ws
    raise exceptions[0]
  File "/usr/local/lib/python3.13/site-packages/pyHomee/__init__.py", line 236, in _ws_receive_handler
    await self._ws_on_message(msg)
  File "/usr/local/lib/python3.13/site-packages/pyHomee/__init__.py", line 271, in _ws_on_message
    await self._handle_message(json.loads(msg))
  File "/usr/local/lib/python3.13/site-packages/pyHomee/__init__.py", line 338, in _handle_message
    self.nodes = [HomeeNode(node_data) for node_data in msg["all"]["nodes"]]
                  ~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyHomee/model.py", line 251, in __init__
    self.remap_attributes()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyHomee/model.py", line 416, in remap_attributes
    self._attribute_map[a.type] = a
                        ^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyHomee/model.py", line 161, in type
    return AttributeType(self._data["type"])
  File "/usr/local/lib/python3.13/enum.py", line 726, in __call__
    return cls.__new__(cls, value)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/enum.py", line 1199, in __new__
    raise ve_exc
ValueError: 222 is not a valid AttributeType

**Comment by Taraman17** [comment]
Hi @neosantos84, das gibt einen ersten Hinweis.
Er stolpert über irgendein unbekanntes Attribut.

Um herauszufinden, welches das ist, bräuchte ich aber doch das komplette Debug  log.

**Comment by neosantos84** [comment]
@Taraman17 : Habe dir das hoffentlich vollständige Protokoll per Mail geschickt

**Comment by Taraman17** [comment]
Ist angekommen und vollständig. Danke!
Das Thema wird allerdings so wie es aussieht etwas komplexer.

Wenn ich das richtig sehe, dann hast du 2 Homees.
Die werden allerdings mit identischen IDs gemeldet, was bei der Zuordnung im Programmcode knifflig werden wird.

Kannst du mir screenshots machen, wie sich die beiden Homees und das Master / Slave Verhältnis in der App oder WebApp darstellen?

Das unbekannte Attribut konnte ich auf die Schnelle noch nicht identifizieren. Kann sein, dass ich da noch eine neue Version basteln muss, die das genauer loggt.

**Comment by neosantos84** [comment]
Okay, Es ist noch etwas komplizierter. Ich habe 3 homees. Im Master sind alle Geräte der beiden Slaves eingebunden. Was es vielleicht noch komplizierter macht, dass man die Geräte im Master dann nochmal umbenennen kann. Da habe ich sicherlich nachträglich noch etwas umbenannt. Ich hatte sogar virtuelle Geräte aus dem Slave im Master. Die habe ich jetzt mal gelöscht. Wie ich das sinnvoll aus der web-app darstellen soll, weiß ich noch nicht. Hast du eine Idee?

**Comment by Taraman17** [comment]
Hmm, das klingt spannend. 😁
VIelleicht wären die Seiten mit den Einstellungen der einzelnen Homees aus der App hilfreich. Wenn da Daten drin sind, die du nicht öffentlich haben magst, gerne auch per Mail.
Die virtuellen Geräte, waren das die für den Homee-Mode? Die hatte ich gesehen und die sollten eigentlich kein Problem machen.

**Comment by neosantos84** [comment]
habs dir lieber per Mail geschickt

**Comment by Taraman17** [comment]
Nach allem was ich jetzt über Master Homees weiß, sollte das Problem eigentlich nicht damit zusammengehangen haben.
