### ISSUE TITLE
Hörmann Serie 3 Garage door does not show Status anymore

### ISSUE THREAD

**Issue by Taraman17** [Taraman17/hass-homee#91]
## Type of problem

- [ ] I have a question.
- [ ] A feature does not work as expected.
- [X] I found a bug (see error log below).

## Detailed description
Hörmann Serie 3 Garage door does not show Status anymore.
The Sensor adding fails

## Error log

```text
Error adding entity None for domain sensor with platform homee

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 716, in _async_add_entity
    entity_name = entity.name
                  ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 734, in name
    return self._name_internal(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 689, in _name_internal
    and (name_translation_key := self._name_translation_key)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 648, in _name_translation_key
    if self.translation_key is None:
       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homee/sensor.py", line 257, in translation_key
    if self.is_reversed(self._measurement.type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homee/__init__.py", line 373, in is_reversed
    if hasattr(attribute.options, "reverse_control_ui"):
               ^^^^^^^^^^^^^^^^^
  File "/config/pymee/model.py", line 159, in options
    return HomeeAttributeOptions(self._data["options"])
                                 ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'options'
```

**Comment by Taraman17** [comment]
The reason was, that I had an old pymee library lying around from testing in my HA config directory and they seem to have reactivated loading these...

Not a bug.
